### ISSUE TITLE
编译时 gee-1.0' not found

### ISSUE THREAD

**Issue by guanghwang** [manateelazycat/deepin-terminal#1]
error: Package `gee-1.0' not found in specified Vala API directories or GObject-Introspection GIR directories

我已经安装 vala 和vte-2.91。

谢谢。

**Comment by manateelazycat** [comment]
请安装  libgee-dev 和 gir1.2-gee-1.0 这两个包再尝试一下。 ;)

**Comment by guanghwang** [comment]
搞定，装了libgee-dev. 谢谢。

**Comment by manateelazycat** [comment]
you're welcome! ；）
