### ISSUE TITLE
Big gap between window and its border when running with KWin

### ISSUE THREAD

**Issue by felixonmars** [manateelazycat/deepin-terminal#10]
![2016-08-19-164554-2195c8](https://cloud.githubusercontent.com/assets/1006477/17804068/892931c4-662c-11e6-83ad-29625b4f7b3c.png)

**Comment by manateelazycat** [comment]
@felixonmars 你的窗管的问题， 我已经按照X11标准， set_decorated(false) 了， 窗管就不应该再绘制边框了。

**Comment by felixonmars** [comment]
这个问题在 deepin-screenshot 也会存在，即窗口被识别的边框远大于它的实际大小，如下图是直接双击窗口截出：

![2016-08-24-132851-fdb9ed](https://cloud.githubusercontent.com/assets/1006477/17919300/1a2e7348-69ff-11e6-94b5-eb18d472026d.png)

**Comment by felixonmars** [comment]
已解决，deepin-screenshot 新版已经支持。
