### ISSUE TITLE
Preference: Widgets are not shown correctly

### ISSUE THREAD

**Issue by felixonmars** [manateelazycat/deepin-terminal#11]
![2016-08-19-164803-77d897](https://cloud.githubusercontent.com/assets/1006477/17804128/cabda020-662c-11e6-9709-c76b72b775b2.png)

**Comment by manateelazycat** [comment]
@felixonmars 大神你的窗管非常的不标准啊！

**Comment by felixonmars** [comment]
下面控件没画出来的问题真的不是窗管的问题……我用 deepin-wm 底下也是一团黑，鼠标飘过能浮现出一部分控件来。

**Comment by felixonmars** [comment]
```
list_files: Error opening directory '/build/deepin-terminal/src/deepin-terminal/theme': No such file or directory
Failed to open file '/build/deepin-terminal/src/deepin-terminal/image/deepin-terminal.svg': No such file or directory**********************
```

确定问题在于 project_path.c 里的路径是编译时路径，安装后不应引用。

**Comment by manateelazycat** [comment]
貌似你已经搞定了。　;)

**Comment by felixonmars** [comment]
这是个 ugly hack，还是希望编译时不要硬编码路径到编译时的目录，至少提供一个选项也好……

**Comment by manateelazycat** [comment]
没有硬编码， 而是根据 project_path.c 所在路径生成的。

2016-08-24 23:39 GMT+08:00 Felix Yan notifications@github.com:

**Comment by felixonmars** [comment]
对发行版来说，编译目录一般不同于运行目录，所以还是希望能至少有个选项来指定它。

2016年8月28日 22:28，"Andy Stewart" notifications@github.com写道：
