### ISSUE TITLE
"Required" characters are wider in the password box than the others

### ISSUE THREAD

**Issue by felixonmars** [manateelazycat/deepin-terminal#13]
![2016-08-24-130251-c0c256](https://cloud.githubusercontent.com/assets/1006477/17918883/70ba5230-69fb-11e6-8594-37e1198c510c.png)

**Comment by manateelazycat** [comment]
因为密码的圆点比字符的宽，　而gtk+的entry只能设置unicode作为圆点，　不能自己绘制。
而　unicode 的圆点要不太大要不太小　（现在用的就是太大的版本），　导致圆点会把字符的间距撑开。

自己像　deepin-ui 绘制entry控件可以解决（但是我为了移植性不想造控件了）。

最后，　通过移除密码框的线索来解决这个问题：　https://github.com/manateelazycat/deepin-terminal/commit/5dd0d17f9d4bcdf8898a3c2a65e6c11c6c44bb4e
