### ISSUE TITLE
Password should not be required when connecting via SSH

### ISSUE THREAD

**Issue by felixonmars** [manateelazycat/deepin-terminal#14]
Pubkey-authentication enabled servers won't need a password.

![2016-08-24-130251-c0c256](https://cloud.githubusercontent.com/assets/1006477/17918917/a2c5e474-69fb-11e6-8d26-0a8cba2925fc.png)

**Comment by manateelazycat** [comment]
有空见面我跟你修吧

**Comment by manateelazycat** [comment]
Fixed by patch https://github.com/manateelazycat/deepin-terminal/commit/1daa779b076baa92508fcc4614403a38a9f33906
