### ISSUE TITLE
Upload/Download file doesn't work in a normal SSH session

### ISSUE THREAD

**Issue by felixonmars** [manateelazycat/deepin-terminal#16]
They work fine in a zssh session, but doesn't work with normal ssh. It is a bit misleading to show the two actions while they fail in silence.

**Comment by manateelazycat** [comment]
zssh 和　ssh 都可以，　你登录以后　foreground process 的　/proc/pid/comm /proc/pid/cmdline 分别是啥？

**Comment by felixonmars** [comment]
![2016-08-24-234505-258b30](https://cloud.githubusercontent.com/assets/1006477/17937474/cdfb7038-6a54-11e6-9a5f-25cf65f029b2.png)
![2016-08-24-234455-a9eecf](https://cloud.githubusercontent.com/assets/1006477/17937475/ce67b8d8-6a54-11e6-899e-85715b3d30ba.png)

**Comment by manateelazycat** [comment]
Have fixed.
