### ISSUE TITLE
Upload/Download actions should be available in a screen/tmux

### ISSUE THREAD

**Issue by felixonmars** [manateelazycat/deepin-terminal#17]
Currently the two actions are not available when running a zssh session inside a local screen/tmux. It should work, though.

**Comment by manateelazycat** [comment]
你登入　screen/tmux 以后，　得到终端里面的进程　foreground process id, 然后粘贴一下　/proc/pid/comm 给我，　我把　screen/tmux 的命令加入到白名单中

**Comment by felixonmars** [comment]
![2016-08-24-234245-a3c66b](https://cloud.githubusercontent.com/assets/1006477/17937390/7e9f91b8-6a54-11e6-9768-790bf1bca36b.png)
![2016-08-24-234230-50b031](https://cloud.githubusercontent.com/assets/1006477/17937391/7ea0d500-6a54-11e6-9d9a-ffb25301ed7b.png)

**Comment by manateelazycat** [comment]
Has fixed in https://github.com/manateelazycat/deepin-terminal/commit/c4546f822c06d2fd2c9bf5e67f85fad31016c2db

Thanks for report!
