### ISSUE TITLE
Follow sshconfig in "Add Server"

### ISSUE THREAD

**Issue by felixonmars** [manateelazycat/deepin-terminal#18]
It would be nice to follow sshconfig and fill in some fields by default when adding a server. For example, if I have the following entry in ~/.ssh/config:

```
Host meow
User meow
Port 8888
```

I would expect port and user fields to be pre-filled when I have entered "meow" in address. And if `User` is not present, the login name of current user would be used just the same way as `ssh` itself.

**Comment by manateelazycat** [comment]
容我有空的时候折腾一下

**Comment by manateelazycat** [comment]
@felixonmars 这个还要解析 ssh 配置文件， 要不你自己挑战一下吧。 ;)

**Comment by manateelazycat** [comment]
这个需求不是和很强烈， 暂时不会做了。
