### ISSUE TITLE
Window shadows are incorrect when restoring from maximum

### ISSUE THREAD

**Issue by felixonmars** [manateelazycat/deepin-terminal#19]
Resizing the window will bring it back to normal.

![2016-08-24-132851-fdb9ed](https://cloud.githubusercontent.com/assets/1006477/17919271/c4dec1a4-69fe-11e6-9c0b-12e4228a81be.png)

**Comment by felixonmars** [comment]
Another problem spotted from the screenshot: The "maximum" button is still highlighted after restoring from maximum.

**Comment by manateelazycat** [comment]
fixed by patch: https://github.com/manateelazycat/deepin-terminal/commit/199d98fc48d57fee8cf167e8b93f27d0dbb57886
