### ISSUE TITLE
Some monospace fonts are not displayed in config

### ISSUE THREAD

**Issue by sonald** [manateelazycat/deepin-terminal#27]
font like mononoki does not have spacing info, so it does not appear in the font list. I believe this can be fixed by a heuristic algorithm: if width(l) == width(m), then it means it's monospace font.

**Comment by sonald** [comment]
有空我就帮你撸了，但是感觉没空：）

**Comment by manateelazycat** [comment]
这边测试 spacing 等于 100 (等宽字体）或者等于 110 (点阵字体） 的就显示出来。
你的意思是说 width 等于 100 的也显示出来？

**Comment by manateelazycat** [comment]
@sonald 有空没？　我要奔向终端　bug free 啦。　:)

**Comment by sonald** [comment]
之前试了一下，用freetype加载每个字体并计算两个字符的宽度是否一样来判断是不是等宽字体是很准确的，问题是太慢了。。。所以不可行。后来我看了看gnome-terminal的字体选择对话框，果然用了很简单的方法，里面有大量飞等宽字体被列出来了，但是好处是不会遗漏字体。 我机器上的一些字体deepin-terminal就列举不出，比如mononoki（没有spacing信息）。

**Comment by manateelazycat** [comment]
@sonald 把字体发过来，　我给你做一个白名单。

**Comment by manateelazycat** [comment]
@sonald I have write patch https://github.com/manateelazycat/deepin-terminal/commit/7eeaec38c6b63b48a7a28e91b669d74400f5332a to support mononoki font, thanks guy. ;)
