### ISSUE TITLE
Quake terminal theme

### ISSUE THREAD

**Issue by pedrozoalencar** [manateelazycat/deepin-terminal#31]
How to change Quake terminal theme?

**Comment by manateelazycat** [comment]
I have add new patch https://github.com/manateelazycat/deepin-terminal/commit/9f2d59a16255e39e643573a90f0f41b5f69afbb8  to fix this problem.

After patch, you can click "switch theme" in right menu of quake terminal.

Thanks for your suggestion! ;)
