### ISSUE TITLE
`Gdk.Monitor' not found while building

### ISSUE THREAD

**Issue by hosiet** [manateelazycat/deepin-terminal#37]
Tried to build from source on Debian unstable.

The full build log is given below.

[deepin-terminal.buildlog.txt](https://github.com/manateelazycat/deepin-terminal/files/491557/deepin-terminal.buildlog.txt)

P.S. The source package is from Deepin official repository.

**Comment by manateelazycat** [comment]
Please install below depend packages before you build it：

Depends: libatk1.0-0 (>= 1.12.4), libc6 (>= 2.2.5), libcairo-gobject2 (>= 1.10.0),
         libcairo2 (>= 1.10.0), libfontconfig1 (>= 2.11), libfreetype6 (>= 2.6),
         libgdk-pixbuf2.0-0 (>= 2.22.0), libgee-0.8-2 (>= 0.8.3), libglib2.0-0 (>= 2.39.4),
         libgnutls30 (>= 3.4.0), libgtk-3-0 (>= 3.19.12), libjson-glib-1.0-0 (>= 0.12.0),
         libpango-1.0-0 (>= 1.14.0), libpangocairo-1.0-0 (>= 1.14.0), libsecret-1-0 (>= 0.7),
         libvte-2.91-0, libwnck-3-0 (>= 2.91.6), libx11-6, libxcb1, zlib1g (>= 1:1.1.4), zssh, lrzsz

**Comment by hosiet** [comment]
OK I will give a try.

Please consider updating README and use -dev packages to control
Build-Depends.

在 2016年9月25日週日 17:53，Andy Stewart notifications@github.com 寫道：

**Comment by hosiet** [comment]
@manateelazycat No, I don't think installing dependency works.

I installed **all** the development packages on your list (which automatically depends those libraries) in a _clean chroot_ environment, but the problem still exists.

Further investigations still needed.

**Comment by hosiet** [comment]
I found that GdkMonitor was introduced in GTK+ 3.22 and I am using 3.21.5.

It would be great if README.md could mention such requirement.

**Comment by hosiet** [comment]
Debian unstable is now under GTK+ 3.22, but the problem remains.

Seems that it is caused by vala 0.34, which broke the vala binding to GTK+ by itself.
Arch Linux did not reproduce such problem since Arch Linux is still using vala 0.32.
