### ISSUE TITLE
Consider removing bundled vapi files

### ISSUE THREAD

**Issue by hosiet** [manateelazycat/deepin-terminal#39]
The bundled files in `vapi/` dir will soon cause troubles, since the release of vala 0.34 will break the GTK binding. The problem in #37 can be solved by removing `vapi/gdk-3.0.vapi` while building.

All files in `vapi/` dir may be deleted except `vapi/fontconfig.vapi`.

**Comment by manateelazycat** [comment]
@sonald Can we remove gdk-3.0.vapi now ? I rember we add gdk-3.0.vapi to make deepin-terminal can build by vala-0.32 that deepin-wm need vala-0.32.

**Comment by sonald** [comment]
vala 0.32 breaks clutter binding which affects deepin-wm. I need to fix this first before remove gtk/gdk binding from vapi

**Comment by manateelazycat** [comment]
@sonald Let me know once you fixed clutter problem, thanks. ;)

**Comment by manateelazycat** [comment]
I have add patch https://github.com/manateelazycat/deepin-terminal/commit/b73eecd11a547e8f051fd8362c4549008061fdd2 to fixed this problem.

Thanks for report!
