### ISSUE TITLE
Cannot scroll

### ISSUE THREAD

**Issue by guanghwang** [manateelazycat/deepin-terminal#4]
I cannot scroll the terminal by mouse.

Platform: deepin 15.2

Below is the screen-shot of my preference.
![deepinscreenshot20160811140648](https://cloud.githubusercontent.com/assets/12839553/17599428/058860f2-5fcd-11e6-958e-4f60dfc076df.png)

Thanks.

**Comment by manateelazycat** [comment]
Please update newest version that haven't this problem.
