### ISSUE TITLE
Lack of HiDPI support for menus

### ISSUE THREAD

**Issue by hosiet** [manateelazycat/deepin-terminal#40]
Currently `deepin-terminal` lacks HiDPI support for fonts and menu in the settings window. The menu won't respect system DPI and scaling settings as well.

I am wondering if it is a problem in `deepin-terminal` or `deepin-menu`, but the problem should be addressed finally.

**Comment by manateelazycat** [comment]
HiDPI work will do at 2017, that all deepin applications will change code to support HiDPI

Why not now? Some deepin applicaiton still use deepin-ui(pygtk), and some application still use QML, we will add HiDPI support when all deepin applications switch to Qt/Widget(C++).

Thanks for suggestion!
