### ISSUE TITLE
Duplicated window border on KDE5 Plasma Desktop

### ISSUE THREAD

**Issue by hosiet** [manateelazycat/deepin-terminal#41]
![hosiet - _057](https://cloud.githubusercontent.com/assets/8443926/19013071/994f5d0a-87f9-11e6-984a-3c9c1acc2bad.png)

A really classic problem when the program is using custom window border.

**Comment by manateelazycat** [comment]
You need disable "gtk+3 decratored" option from your kde, it's a problem of KDE that force window decroated for all Gtk+3 applicaitons.

**Comment by hosiet** [comment]
Not really. You may try to run `gnome-tweak-tool` or `gnome-control-center` on KDE Plasma, both of which are performing well with no extra border.

At least we should try to let the KWin's automatically-added border fit the inner window and squash the empty between :)

**Comment by manateelazycat** [comment]
@hosiet 原来Arch的肥猫就跟我说过这个问题， 这个需要在KDE设置中心关闭 gtk3 decorated 强制边框的选项就可以修复。 

真的不知道 KDE 为什么这么仇视 Gtk3 应用

**Comment by iceqing** [comment]
If you are using manjaro KDE, just do this:

![image](https://user-images.githubusercontent.com/39587710/61865728-4f808c80-af06-11e9-974a-645d41c71fb9.png)

@manateelazycat Thanks a lot.
