### ISSUE TITLE
Unneeded execution permission for files in theme/ directory

### ISSUE THREAD

**Issue by hosiet** [manateelazycat/deepin-terminal#42]
Setting file permission to 755 is definitely a mistake. Please correct it.

**Comment by manateelazycat** [comment]
In your point, right file permission should be? 
I will check files to correct it.

Thanks!

**Comment by hosiet** [comment]
Should be 644, which is the same as doing `chmod a-x` on all those files.

P.S. I found that image/tab_add_dark_hover.png, image/tab_add_dark_normal.png, image/tab_add_dark_press.png are also 755, which should be fixed together as well.

**Comment by manateelazycat** [comment]
@hosiet When i change permission, git status will failed.

I'm happy if you give me some pull request. ;) 

Thanks.

**Comment by manateelazycat** [comment]
Have merged your request, thank you very much!
