### ISSUE TITLE
Consider switching to a better buildsystem

### ISSUE THREAD

**Issue by hosiet** [manateelazycat/deepin-terminal#43]
The current build system, which is made up with raw Makefile + shell scripts, looks hacky. It may be better if the project could switch to a proper buildsystem, e.g., CMake, waf or Autotools. A sane build system helps the packagers and makes it easier to deal with the project.

I made a demo, https://github.com/hosiet/deepin-terminal/tree/master , in which I tried to migrate deepin-terminal to use Autotools and everything works fine. There might be easier solutions other than Autotools, and CMake should be a good choice.

**Comment by cdluminate** [comment]
Thanks. Your build system works for me

following command are in reverse order.

```
./deepin-terminal 
ls
make
./configure
autoreconf
automake --add-missing
autoscan
```

**Comment by manateelazycat** [comment]
@hosiet Can you give me some pull request ? I will check later, thanks!

**Comment by manateelazycat** [comment]
@hosiet I have switch deepin-terminal's compile script from Makefile to CMake, thanks for your suggestion!
