### ISSUE TITLE
Add Keypath Selection when adding new server

### ISSUE THREAD

**Issue by Nhoya** [manateelazycat/deepin-terminal#44]
Hey there, 
actually i have a little problem using the Remote Management, i can't use different identities because it will load only the key from .ssh, can you add an option per server for selecting the SSH key to use while connecting to the specified server?

**Comment by manateelazycat** [comment]
I will implement this feature in next version.

**Comment by manateelazycat** [comment]
Same bug as https://github.com/manateelazycat/deepin-terminal/issues/14, close duplicated bug.

Thanks for report!
