### ISSUE TITLE
深度终端能否支持保存工作区？

### ISSUE THREAD

**Issue by slevinsc** [manateelazycat/deepin-terminal#52]
类似于浏览器每次启动能打开上次启动的页面。还有能否支持工作区重命名或者工作区打开远程服务器，它的名字为远程服务器的名字

**Comment by manateelazycat** [comment]
这个因为标签里面会自动打开程序或远程服务器，　这个功能不会做。

浏览器之所以能够做是因为浏览器只用打开每个标签的页面就可以了，　终端不会监听用户的命令自动敲命令或输入密码的，　如果只是恢复空白标签也用处不大。
