### ISSUE TITLE
能否支持仅关闭工作区里面的单个分屏？

### ISSUE THREAD

**Issue by choldrim** [manateelazycat/deepin-terminal#53]
有时候在某个工作区里面的某个分屏的ssh因为网络问题断开了，任何中断信号已经发送不了了，需要强制关闭，但是当前终端应该只是支持整个工作区的关闭吧？
就是不想因为一个分屏挂掉了，需要强制关闭时把整个工作区都关掉。

**Comment by manateelazycat** [comment]
Ctrl + Alt + q 就可以关闭当前分屏窗口， 所有按键可以按 Ctrl + Shift + / 查看。

在 2016年11月20日 上午10:56，Caijun <notifications@github.com>写道：
