### ISSUE TITLE
wrong new workspace location while reading man manual

### ISSUE THREAD

**Issue by choldrim** [manateelazycat/deepin-terminal#55]
deepin-terminal open a new workspace with `/usr/share/man` location while I am reading man manual and not matter where the prev workspace locate.

**Comment by choldrim** [comment]
version: 2.1.5-1

**Comment by manateelazycat** [comment]
@choldrim 没看懂你写的， 中文？ ;)

**Comment by choldrim** [comment]
`  - -|  `
重现方式：
- 使用`man ls` (或者其他的manual手册都可以)
- 新建一个工作区
- 发现工作区的位置不是之前的工作区的位置，而是`/usr/share/man`

期望结果：
工作区的位置应该和之前的工作区的位置保持一致，而非 `/usr/share/man`

**Comment by manateelazycat** [comment]
Fixed by https://github.com/manateelazycat/deepin-terminal/commit/c06f98b1898dce30bd3f2e77c69fd4ad423e5972
