### ISSUE TITLE
[Feature Request] auto-close feature in dropdown-terminal

### ISSUE THREAD

**Issue by ceyhunn** [manateelazycat/deepin-terminal#56]
When deepin-terminal is opened like dropdown-terminal and then loses the focus, it would be nice to add auto-close feature. Not quit the terminal , just running in background...

Thanks for your hard work!!!

**Comment by manateelazycat** [comment]
@ceyhunnabiyev Hi, today re-think about your suggestion.
I add new patch to implement this feature: https://github.com/manateelazycat/deepin-terminal/commit/4f7069e064ae4e5437013295fd5bdbfd8867086c

You can try install this package: https://ci.deepin.io/job/deepin-terminal-2.0-ci/563/artifact/deepin-terminal_2.1.12+r_amd64.deb

This version will update in next system upgrade.

Thanks for your suggestion!

**Comment by ceyhunn** [comment]
@manateelazycat  many thanks for this, I use latest  Archlinux, Deepin DE.. Can you please upgrade this for Archlinux??
