### ISSUE TITLE
"KEY_UNKNOWN" event causes deepin-terminal to crash

### ISSUE THREAD

**Issue by shreyanshk** [manateelazycat/deepin-terminal#62]
Keycode 240 causes crash. The error message is "segfault at 0 ip 0000000000461856 sp 00007ffc9aecbb90 error 4 in deepin-terminal[400000+94000]"
After extensive debugging, I've managed to narrow down to the event which causes this crash and then reproduce this event on gnome-terminal. Here is relevant output from showkey, evtest and GDB to help with the debugging.

showkey (on gnome-terminal):
kb mode was ?UNKNOWN?
[ if you are trying this under X, it might not work
since the X server is also reading /dev/console ]

press any key (program terminates 10s after last keypress)...
keycode  28 release
keycode 240 press
keycode 240 release

evtest (on gnome-terminal):
Testing ... (interrupt to exit)
Event: time 1489747340.878990, type 4 (EV_MSC), code 4 (MSC_SCAN), value cf
Event: time 1489747340.878990, type 1 (EV_KEY), code 240 (KEY_UNKNOWN), value 1
Event: time 1489747340.878990, -------------- SYN_REPORT ------------
Event: time 1489747340.879022, type 1 (EV_KEY), code 240 (KEY_UNKNOWN), value 0
Event: time 1489747340.879022, -------------- SYN_REPORT ------------

gdb (on gnome-terminal):
shreyansh@invariant ~/deepin-terminal/build (git)-[master] % gdb deepin-terminal                                                                                                                              v62%
GNU gdb (GDB) 7.12.1
Copyright (C) 2017 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-pc-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from deepin-terminal...done.
(gdb) break widgets_term_on_key_press
Breakpoint 1 at 0x45ee51: file /home/shreyansh/deepin-terminal/build/widget/terminal.c, line 2699.
(gdb) run
Starting program: /home/shreyansh/deepin-terminal/build/deepin-terminal 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/usr/lib/libthread_db.so.1".
[New Thread 0x7fffe935b700 (LWP 24817)]
[New Thread 0x7fffe8b5a700 (LWP 24818)]
[New Thread 0x7fffe3fff700 (LWP 24819)]
[New Thread 0x7fffe25e9700 (LWP 24820)]
[Thread 0x7fffe25e9700 (LWP 24820) exited]

Thread 1 "deepin-terminal" hit Breakpoint 1, _widgets_term_on_key_press_gtk_widget_key_press_event (_sender=0x8ffe10, event=0x7fffdc006e40, self=0xa38b10)
    at /home/shreyansh/deepin-terminal/build/widget/terminal.c:722
722		result = widgets_term_on_key_press ((WidgetsTerm*) self, _sender, event);
(gdb) print *event
$1 = {type = GDK_KEY_PRESS, window = 0x6fd650, send_event = 0 '\000', time = 18217762, state = 16, keyval = 0, length = 0, string = 0xc08e30 "", hardware_keycode = 248, group = 0 '\000', is_modifier = 0}
(gdb) continue
Continuing.
[Thread 0x7fffe3fff700 (LWP 24819) exited]

Thread 1 "deepin-terminal" received signal SIGSEGV, Segmentation fault.
0x000000000045fb11 in widgets_term_on_key_press (key_event=<optimized out>, widget=<optimized out>, self=0xa38b10) at /home/shreyansh/deepin-terminal/build/widget/terminal.c:3360
3360			_tmp140_ = strlen (_tmp139_);

**Comment by manateelazycat** [comment]
From the stack, this is really a bug. Can you write about the reproduction steps? As long as I can reproduce the problem, I can fix it. 

Thank you very much for your feedback!

**Comment by shreyanshk** [comment]
I can reproduce it 100% of time simply by following these steps:
1) launch deepin-terminal
2) connect the laptop charger or press Fn+F8, which is the hardware button for screen switch.

note: deepin-terminal must be the focused window, in other words, these events must be sent to deepin-terminal window. Otherwise, nothing will happen as the events are not delivered to deepin-terminal.

**Comment by manateelazycat** [comment]
My laptop without hardware switch, I find my colleagues to help test tomorrow.

I will let you know once i have process.

**Comment by manateelazycat** [comment]
@shreyanshk I can't reproduce this bug. :(

**Comment by shreyanshk** [comment]
Firstly, is there anything else we can do, like some experimental/testing build which I can test on my computer?

Second, Let me help you with debugging by providing with more hardware details.
I have ASUS GL552VX computer and an up to date Arch Linux installation.
We know hardware switches are implemented with Microsoft's WMI interface. The hardware/bios produces "events" which are transferred to OS by a form of a virtual keyboard. Modern computers implements almost all of the common functions such as keyboard lights, screen brightness, volume control, play/pause on the keyboard.
What is happening on my computer is that there are no crashes whenever I press keyboard led switches, screen brightness, volume control or play/pause etc. Currently, only 2 WMI events are causing issues, as of my knowledge, which are: connecting charger(as mentioned above) & Fn+F7 (for screen on/off).
For the record, gnome-terminal, uxvrt, Konsole xterm and many other terminals that I've tried do not crash like deepin-terminal and show no erratic behaviour.
Please solve this and do not hesitate to ask more questions because deepin-terminal is best and I'd like to continue using it.
Thank you.

**Comment by manateelazycat** [comment]
@shreyanshk I can't reproduce this bug, anyway i add patch https://github.com/manateelazycat/deepin-terminal/commit/e0e11e2fbdb8de4a66c191c1eafac48f1fc64da2 to print code point.

Can you compile git version and then use other terminal to start deepin-terminal, when deepin-terminal crash, give me output such as "Code at test xx point".

I will guess which code is wrong, thank you very much!

**Comment by shreyanshk** [comment]
Code at test 1 point.
Code at test 2 point.
Code at test 3 point.
Code at test 4 point.
Code at test 6 point.
Code at test 7 point.
Code at test 8 point.
Code at test 9 point.
[1]    6360 segmentation fault (core dumped)  ./deepin-terminal

**Comment by manateelazycat** [comment]
@shreyanshk I have write new patch https://github.com/manateelazycat/deepin-terminal/commit/4f03667d8d1544ac41a0a0ca0b6fd49da7031eb9 to fix your crash problem.

Can you help me test this patch? 

Thanks!

**Comment by shreyanshk** [comment]
Can confirm deepin-terminal no longer crashes.

**Comment by manateelazycat** [comment]
@shreyanshk Great, thanks for help . ;)
