### ISSUE TITLE
Deepin terminal + Cinnamon

### ISSUE THREAD

**Issue by bigbruno** [manateelazycat/deepin-terminal#63]
I really like Deepin Terminal and Cinnamon, but in Cinnamon if click in one tab or in + to create new tab, mouse change to drag window.

Ever when change tab need two clicks, and need slow two click, because if make two click fast, window is maximized.

**Comment by manateelazycat** [comment]
Has fixed by https://github.com/manateelazycat/deepin-terminal/commit/baab66c3303b3f5595cae0b5b97ec8d501f95af7

It's my stupid fault, thank you very much for your feedback.

**Comment by bigbruno** [comment]
Thank you, i'm test 2.2.7 and really work good.
