### ISSUE TITLE
I changed some parts of the interface

### ISSUE THREAD

**Issue by avently** [manateelazycat/deepin-terminal#70]
@manateelazycat, hello. I love deepin-terminal and wanted to make it even better. So i decided to change some parts of the interface so it will look "native" in i3WM and made deepin terminal built-in themes usable in menu.
- i hid terminal logo from top-left corner. 
- hid buttons from top-right corner only for i3WM (i can add all tiled WM to the list).
- hid shadow under titlebar.
- replaced your menu implementation with Gtk implementation (because it is easy to customsize and i hate 60 MB of deepin-menu in RAM).
- hid shadow under terminal window (you may not like this change...) because with that shadow terminal looks bad in tiled window managers. There was a huge blank space between window and corners.
- showed "Change theme" button in right click menu.
- made menu with CSS colors from built-in themes (background and foreground colors).

Now it looks brilliant! Please, look at the videos in the archive. I can make pull request if you will like this changes. 

[deepin-terminal.zip](https://github.com/manateelazycat/deepin-terminal/files/1386085/deepin-terminal.zip)

**Comment by manateelazycat** [comment]
@avently 
First, thanks for your great work, and glad you love deepin-terminal.

But i perhaps won't merge your patches.
Because deepin-terminal is design for deepin linux, it's need follow the design standard of deepin.

I use tile-wm (such as i3, xmonad, awesome etc) too much at many years ago, i completely understand those code change, to make it's perfect for tile-wm, it's really great work.

At last, i can't merge your patches, please understand why i can't.

Thanks agian, happy hacking.

**Comment by avently** [comment]
@manateelazycat yes, I understand. Also I understand that terminal can be used on any WM and if people will use it on daily basis like me they will want to look at other deepin solutions (like Deepin Linux). Everyone will win if your terminal will look native for every operating system. 

For example, I can make a check for WM. If a user use "deepin" wm, I will show your current styled menu (I can make gtk.menu identical to qt menu). In other situation I will show colored menu. 

But if you want to limit users of your app to users of deepin wm, ok.

**Comment by avently** [comment]
@manateelazycat i made a fork of your repo with my changes. Feel free to use my code. For example, custom themes support. Themes can be located at ~/.config/deepin/deepin-terminal/theme/
https://github.com/avently/terminal
