### ISSUE TITLE
trouble with remote administration

### ISSUE THREAD

**Issue by treeman1111** [manateelazycat/deepin-terminal#72]
I've tried adding a server that I'd like to ssh into through the remote administration dialog in deepin-terminal version 2.7 running on Manjaro stable. When I try clicking on the added server, though, I get the following error:
`spawn zssh -X -o ServerAliveInterval=60 <server name / user removed for security reasons> -p 22 -o PubkeyAuthentication=no -t echo Bienvenido a Terminal Deepin, asegúrese de que los comandos rz y sz se han instalado en el servidor antes de hacer clic derecho para subir y descargar archivos. &&ssh && exec $SHELL -l
couldn't execute "zssh": no such file or directory
    while executing
"spawn zssh -X -o ServerAliveInterval=60 $user@$server -p $port -o PubkeyAuthentication=$authentication -t echo Bienvenido a Terminal Deepin, asegúres..."
    ("eval" body line 1)
    invoked from within
"eval spawn $ssh_cmd $ssh_opt $private_key -t $remote_command exec \\\$SHELL -l"
    (file "/tmp/deepin-terminal-FHD48Y" line 50)`

Am I just missing some package, or is there a typo, where 'zssh' should be 'ssh?'

**Comment by treeman1111** [comment]
Read that lrzsz was a dep and installed. Still seeing issue.

**Comment by zhtengw** [comment]
You need the package “zssh”. https://aur.archlinux.org/packages/zssh/

Best Regards,
Aten Zhang
