### ISSUE TITLE
Reset  bottom is not centralized

### ISSUE THREAD

**Issue by guanghwang** [manateelazycat/deepin-terminal#8]
设置界面最后的reset按钮是位于整个界面的中间，但不是右边部分的中间。看起来感觉有点歪。是否跟about 上的deepin terminal的图标对齐会更好看？

谢谢。
![deepinscreenshot20160813164754](https://cloud.githubusercontent.com/assets/12839553/17645494/c27b6f52-6175-11e6-9d2a-544118e109c0.png)

**Comment by reionwong** [comment]
@guanghwang 已经在中间了好吗。

**Comment by Lyvnee** [comment]
我这边也没问题。 话说老王昨晚是不是没休息？

**Comment by manateelazycat** [comment]
已经修复了， 谢谢大家报告！ ;)
