### ISSUE TITLE
ELF file should be placed in /usr/lib instead of /usr/share

### ISSUE THREAD

**Issue by felixonmars** [manateelazycat/deepin-terminal#9]
deepin-terminal E: ELF file ('usr/share/deepin-terminal/main') outside of a valid path.

**Comment by manateelazycat** [comment]
@felixonmars 没看懂, 什么意思？

**Comment by felixonmars** [comment]
二进制文件应该在 /usr/lib，平台无关的文件才放在 /usr/share

**Comment by manateelazycat** [comment]
won't fixed.
